import { expect, test } from '@playwright/test';

test('camera starts with packed same-origin hand assets', async ({ context, page, baseURL }) => {
  if (!process.env.PLAYWRIGHT_PREVIEW) test.skip(true, 'Packed assets are generated by the production build.');
  if (baseURL) await context.grantPermissions(['camera'], { origin: new URL(baseURL).origin });

  const requestedPaths: string[] = [];
  page.on('request', (request) => requestedPaths.push(new URL(request.url()).pathname));
  await page.goto('/');
  await page.locator('#hand-control-toggle').click();
  await page.locator('[data-action="start"]').click();

  await expect(page.locator('[data-hand-status-message]')).toContainText(
    /Camera is on|摄像头已开启/,
    { timeout: 45_000 }
  );
  expect(requestedPaths.some((path) => path.endsWith('/hand-assets.json'))).toBeTruthy();
  expect(requestedPaths.some((path) => /\/hand-assets\/.+\.gz$/.test(path))).toBeTruthy();
  expect(requestedPaths.some((path) => path.endsWith('/models/gesture_recognizer.task'))).toBeFalsy();
  expect(requestedPaths.some((path) => path.endsWith('.wasm') && path.includes('/mediapipe/wasm/'))).toBeFalsy();

  await page.locator('[data-action="stop"]').click();
});
